#!/bin/sh

set -eu

exec 2>&1

COMMAND=/usr/local/bin/smtp-brd

# Check command is executable or not
test -x ${COMMAND} || (echo "err: command ${COMMAND} is not executable." && exit 1)

UMASK_SET=${UMASK_SET:-000}
# Allow groups to change files.
# umask 002

umask ${UMASK_SET}

echo "start the app"
# print the app version info
s6-setuidgid $PUID:$PGID ${COMMAND} --version

# start the app
exec s6-setuidgid $PUID:$PGID ${COMMAND}
